<a href="https://colab.research.google.com/github/bekdata/mohirdev_datascines/blob/main/_002%7CNumPy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [5]:
data = [10,20,30,40,50,60,70]   # list
arr = np.array(data)    # array
print(arr)

[10 20 30 40 50 60 70]


In [6]:
data2 = (10,20,30,40,50,60,70,80,90) # tuple
arr2 = np.array(data2)      # arr
print(arr2)

[10 20 30 40 50 60 70 80 90]


In [8]:
arr.ndim  #massiv o`lchamini chiqarish

1

### ikki va undan ortiq massivar uchun

In [12]:
arr3 = [[10,20,30],[40,50,60],[70,80,90]]    # ikki o`lchamli massivni yaratish
arr3 = np.array(arr3)
print(arr3)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [13]:
arr3.ndim   # ikki o`chamli massiv o`lchami

2

In [14]:
arr3.size   # arraydagi elementlar sonini hisoblash

9

In [17]:
# zeros 0 bilan elementlarni chiqarish
arr4 = np.zeros((2,4))    #massiv elemetlari 0 dan iborat bo`lgan
print(arr4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
arr5 = np.ones((4,2))    #elementlari 1 bolgan elementlar sonidan iborat bo`lgan massiv
print(arr5)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [26]:
arr6 = np.arange(2,20,2)
arr6

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
import numpy as np

arr8 = np.random.rand(2, 4)
print(arr8)


[[0.02917429 0.97654387 0.94914843 0.39627215]
 [0.35457883 0.37131929 0.16308242 0.45442144]]
