<a href="https://colab.research.google.com/github/bekdata/mohirdev_datascines/blob/main/_004%7CIndekslash_va_kesish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
data = np.arange(1,10,1)
data

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
sliced_arr = data[2:5]
sliced_arr    # data elementlaridan kesib olish

array([3, 4, 5])

In [ ]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2  # ikki o`lchamli massiv

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr2[1,:]     #ikkinchi qator hamma elementini chaqirish

array([4, 5, 6])

### array 3d

In [26]:
# 3D array   | uch o`lchamli massiv hosil qilish va uni chiqarish
array3d = np.array([[[ 0,  1,  2],
                   [ 3,  4,  5],
                   [ 6,  7,  8]],

                  [[ 9, 10, 11],
                   [12, 13, 14],
                   [15, 16, 17]],

                  [[18, 19, 20],
                   [21, 22, 23],
                   [24, 25, 26]]])
array3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [28]:
array3d[1][1,:]     # uch o`lchamli massivning turli elementlar bilan ikki o`lchamli massiv orqali chqirib oiish va undan foydalanish

array([12, 13, 14])