<a href="https://colab.research.google.com/github/bekdata/mohirdev_datascines/blob/main/_005%7C_Indekslash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np


In [3]:
ismlar = ['ali', 'vali', 'hasan', 'husan']
type(ismlar)   # ro`yxat element

list

In [13]:
data = np.array(ismlar)
data

array(['ali', 'vali', 'hasan', 'husan'], dtype='<U5')

In [14]:
# elementning mavjutigini tekshirish
data == 'ali'

array([ True, False, False, False])

In [22]:
arr1 = np.random.rand(7,4)
arr1

array([[0.14730009, 0.8007411 , 0.18961392, 0.15523013],
       [0.06101967, 0.95066544, 0.60384228, 0.08807549],
       [0.80355282, 0.95128705, 0.03197359, 0.49347348],
       [0.48680701, 0.8495718 , 0.53755772, 0.99902272],
       [0.64828273, 0.43698818, 0.22060818, 0.93722203],
       [0.84487925, 0.79404556, 0.08763967, 0.39185595],
       [0.08348335, 0.10980847, 0.84469503, 0.27786507]])

In [23]:
arr1[arr1 < 0] = 0

In [24]:
arr1

array([[0.14730009, 0.8007411 , 0.18961392, 0.15523013],
       [0.06101967, 0.95066544, 0.60384228, 0.08807549],
       [0.80355282, 0.95128705, 0.03197359, 0.49347348],
       [0.48680701, 0.8495718 , 0.53755772, 0.99902272],
       [0.64828273, 0.43698818, 0.22060818, 0.93722203],
       [0.84487925, 0.79404556, 0.08763967, 0.39185595],
       [0.08348335, 0.10980847, 0.84469503, 0.27786507]])