<a href="https://colab.research.google.com/github/bekdata/mohirdev_datascines/blob/main/_006%7C_massiv_o%60qlarini_almashtirish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
data = np.arange(6).reshape(3,2)
data

array([[0, 1],
       [2, 3],
       [4, 5]])

In [9]:
arr1 = np.random.randn(3, 2)
arr1

array([[ 0.91240283, -0.48335903],
       [ 0.96442836, -1.39260007],
       [-0.00545254, -2.62800932]])

### transpose  *massivning ustun va satr q....

In [10]:
data.T  # ustun va satr qiymatlari o`rnini almashtirish

array([[0, 2, 4],
       [1, 3, 5]])

In [12]:
data.swapaxes(1, 0)

array([[0, 2, 4],
       [1, 3, 5]])

In [11]:
arr1.T

array([[ 0.91240283,  0.96442836, -0.00545254],
       [-0.48335903, -1.39260007, -2.62800932]])

In [14]:
np.dot(arr1.T, arr1)

array([[ 1.76263072, -1.76975182],
       [-1.76975182,  9.07940387]])