<a href="https://colab.research.google.com/github/bekdata/mohirdev_datascines/blob/main/_007%7Cuniversal_funksiyalar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [5]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.sqrt(arr)    # har bir massiv elementdidan kvadrat ildiz olish

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [9]:
np.square(arr)   # har bir massivni kvadratga oshirish

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [11]:
qoldiq, butuna = np.modf(arr)     # qoldiq va butun qismlarga ajratish

In [15]:
nump = np.random.rand(10)
nump

array([0.73129098, 0.24680594, 0.38755521, 0.95962591, 0.10534867,
       0.03926533, 0.24524939, 0.91469047, 0.21848822, 0.56842153])

In [16]:
np.sign(arr)    # musbat qiymatlarga +1, manfiy qiymatlarga -1 qiymatni qaytaadi

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [18]:
arr2 = np.random.randn(6)
arr2

array([-0.06782612, -1.96342356,  0.00874183,  0.55737475,  0.59177777,
        1.63284649])

In [21]:
np.isnan(arr2)  # massivda NaN qiymatlar mavjud bo`lsa True qaytaradi

array([False, False, False, False, False, False])