<a href="https://colab.research.google.com/github/bekdata/mohirdev_datascines/blob/main/_008%7Cmantiqiy_shart_operatorlari.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

In [8]:
arr = np.random.randn(4,4)     # masiv yaratish
arr

array([[ 0.83436607,  0.12982678,  1.69197985, -0.4173985 ],
       [-1.74836872, -0.2802556 , -0.36535395,  0.83281336],
       [ 0.42156429,  0.66403654, -1.26185089,  0.84951679],
       [ 0.11856119, -0.08698919, -0.23292735, -0.19939762]])

In [13]:
result = np.where(arr<0, -1, 1)    #qiymat <0 bolsa =-1, yoki >1 bo`lsa =+1 deb nomlangan kod
result

array([[ 1,  1,  1, -1],
       [-1, -1, -1,  1],
       [ 1,  1, -1,  1],
       [ 1, -1, -1, -1]])

In [17]:
arr2 = np.random.randn(4,4)
arr2

array([[-0.0453945 , -0.07750009,  2.17648017, -0.97074444],
       [ 0.17826584,  0.06917384, -1.40587023, -0.69553121],
       [-1.35688307,  0.50403596,  1.18427412, -0.31150341],
       [ 0.43905238, -0.36859837,  0.98465292, -0.44163774]])

In [21]:
result2 = np.where(arr2<0, -4, 5)    # qiymat musbat bo`lsa =5, manfiy bolsa -4 ga teng
result2

array([[-4, -4,  5, -4],
       [ 5,  5, -4, -4],
       [-4,  5,  5, -4],
       [ 5, -4,  5, -4]])