<a href="https://colab.research.google.com/github/bekdata/mohirdev_datascines/blob/main/_009%7C_arifmetik_amallar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
arr1 = np.arange(6).reshape(2,3)
arr2 = np.arange(6,12).reshape(2,3)

In [7]:
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
arr2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
arr1 + arr2   # massivning mos elementlarini qo`shish

array([[ 6,  8, 10],
       [12, 14, 16]])

In [14]:
arr = arr1 - arr2
arr

array([[-6, -6, -6],
       [-6, -6, -6]])

In [21]:
arr1 * arr2  # massiv elementlarni ko`paytirish

array([[ 0,  7, 16],
       [27, 40, 55]])

In [22]:
arr1**2    # massivni darajaga ko`tarish

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [24]:
arr2**0.5    # massiv ildiz qiymat olish

array([[2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])

In [25]:
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
arr3 = np.arange(3).reshape(1,3)
arr3

array([[0, 1, 2]])

In [32]:
print(arr1.shape)    # turli xil o`lchamdagi massivlarda
print(arr3.shape)
arr1  + arr3     # mos qiymatlar ustida amallar bajariladi ekan

(2, 3)
(1, 3)


array([[0, 2, 4],
       [3, 5, 7]])