<a href="https://colab.research.google.com/github/bekdata/mohirdev_datascines/blob/main/_010%7C_matematik_va_statik_amallar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#data
arr = np.random.randn(5, 4)
arr

array([[-0.96578858,  0.17188016, -0.81971239, -0.04694568],
       [ 0.3594543 ,  0.68023242,  1.50846214, -0.30465125],
       [ 0.43868262, -0.03296435,  0.29085251, -0.12591781],
       [-0.68463484, -0.30662626,  0.87868533,  1.10064599],
       [ 2.86793619, -0.61088078, -0.44360355, -0.42437394]])

In [ ]:
print(arr.sum())   # arr massivning barcha elementlari yig`indisini hisoblab beradi
print(np.sum(arr))   # 2-usul

3.5307322262092655
3.5307322262092655


In [ ]:
arr.sum(axis = 1)    # qator ma`lumotlari bo`yicha yig`indini hisoblaydi

array([-1.66056649,  2.24349761,  0.57065297,  0.98807023,  1.38907791])

In [ ]:
arr.sum(axis = 0)    #ustun ma`lumotlari bo`yicha yig`indini hisoblaydi

array([ 2.01564969, -0.09835881,  1.41468403,  0.19875732])

In [ ]:
# mean -` o`rta arifmetik qiymatni hisoblaydi
data = np.arange(5)
print(data)
print(data.mean())     # data malumotlari o`rta arifmetigi

[0 1 2 3 4]
2.0
