<a href="https://colab.research.google.com/github/bekdata/mohirdev_datascines/blob/main/_012%7C_pandas_series_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [2]:
from pandas import Series,DataFrame as df

In [5]:
obj = Series([3,6,9,12])     # series elementini hosil qilish
obj

0     3
1     6
2     9
3    12
dtype: int64

In [8]:
obj.values    # qiymat ma`lumotlarini ajratib olish

array([ 3,  6,  9, 12])

In [7]:
data = Series([1,2,3,4],index=['a','b','c','d'])
data

a    1
b    2
c    3
d    4
dtype: int64

In [15]:
print(data.index)
print(data.values)

Index(['a', 'b', 'c', 'd'], dtype='object')
[1 2 3 4]


In [17]:
data["a"]   # elementlarni indeksi bo`yicha chaqirib olish

1

In [19]:
data[data>2]    # series elementlari o`rtasida tartiblash

c    3
d    4
dtype: int64

In [20]:
data * 2   # elementni har bir qism bo`yicha bazi qiymatga ko`tarish

a    2
b    4
c    6
d    8
dtype: int64

In [22]:
# lug`at malumotlardan series element yaratish
cars = {'one':1, 'two':2,'there':3, 'four':4,'five':5}
data2 = Series(cars)
data2

one      1
two      2
there    3
four     4
five     5
dtype: int64

In [23]:
# Series ichida elementning mavjudligini tekshirish
'one' in cars

True

In [26]:
# lug`at elementlarining qiymatlarini chiqarish
print(cars['one'])
print(cars['two'])

1
2


In [28]:
print(data.values)
print(data2.index)

[1 2 3 4]
Index(['one', 'two', 'there', 'four', 'five'], dtype='object')


In [29]:
data.isnull()    # seriesda mavjud bo`lmagan qiymatlarni aniqlash

a    False
b    False
c    False
d    False
dtype: bool

In [35]:
data2.index.name = "Numbers"     # ustunga nom berish
data2

Numbers
one      1
two      2
there    3
four     4
five     5
dtype: int64

In [36]:
data2.shape    # series o`lchamini chiqarish

(5,)

In [37]:
data2.size    # series elementlar sonini chiqarish

5

In [41]:
# loc parametridan foydalanish
print(data2.loc['one'])    # ustun nomidan chiqarish
print(data2.loc['two'])

1
2


In [44]:
data2.iloc['two']

TypeError: Cannot index by location index with a non-integer key